package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"

	"github.com/google/uuid"
	"github.com/n0m-d/DVAPI/graph/model"
	"github.com/n0m-d/DVAPI/internal/domain"
	"github.com/n0m-d/DVAPI/internal/service"
)

// CreateNote is the resolver for the createNote field.
func (r *mutationResolver) CreateNote(ctx context.Context, input model.NewNote) (*model.Note, error) {
	userID, err := uuid.Parse(input.UserID)
	if err != nil {
		return nil, fmt.Errorf("%w: invalid user id", service.ErrInvalidInput)
	}
	note, err := r.NoteService.Create(ctx, domain.CreateNoteInput{
		UserID: userID,
		Title:  input.Title,
		Body:   input.Body,
	})
	if err != nil {
		return nil, err
	}
	return toModelNote(note), nil
}

// UpdateNote is the resolver for the updateNote field.
func (r *mutationResolver) UpdateNote(ctx context.Context, id string, input model.UpdateNote) (*model.Note, error) {
	noteID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("%w: invalid note id", service.ErrInvalidInput)
	}
	note, err := r.NoteService.Update(ctx, noteID, domain.UpdateNoteInput{
		Title: input.Title,
		Body:  input.Body,
	})
	if err != nil {
		return nil, err
	}
	return toModelNote(note), nil
}

// DeleteNote is the resolver for the deleteNote field.
func (r *mutationResolver) DeleteNote(ctx context.Context, id string) (bool, error) {
	noteID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("%w: invalid note id", service.ErrInvalidInput)
	}
	if err := r.NoteService.Delete(ctx, noteID); err != nil {
		return false, err
	}
	return true, nil
}

// Notes is the resolver for the notes field.
func (r *queryResolver) Notes(ctx context.Context, userID *string) ([]*model.Note, error) {
	var filter *uuid.UUID
	if userID != nil && *userID != "" {
		parsed, err := uuid.Parse(*userID)
		if err != nil {
			return nil, fmt.Errorf("%w: invalid user id", service.ErrInvalidInput)
		}
		filter = &parsed
	}
	notes, err := r.NoteService.List(ctx, filter)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Note, 0, len(notes))
	for _, n := range notes {
		out = append(out, toModelNote(n))
	}
	return out, nil
}

// Note is the resolver for the note field.
func (r *queryResolver) Note(ctx context.Context, id string) (*model.Note, error) {
	// noteID, err := uuid.Parse(id) // Type comment for SQLi vuln
	// if err != nil {
	// 	return nil, fmt.Errorf("%w: invalid note id", service.ErrInvalidInput)
	// }
	note, err := r.NoteService.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return toModelNote(note), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)

func toModelNote(n domain.Note) *model.Note {
	return &model.Note{
		ID:        n.ID.String(),
		UserID:    n.UserID.String(),
		Title:     n.Title,
		Body:      n.Body,
		CreatedAt: n.CreatedAt,
		UpdatedAt: n.UpdatedAt,
	}
}
