// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assignments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeOverdueAssignments = `-- name: CloseOverdueAssignments :many
UPDATE assignments
SET status = 'closed',
    updated_at = now()
WHERE due_date < now()
  AND status = 'published'
RETURNING id, course_id, title, description, due_date, status, created_at, updated_at, created_by
`

func (q *Queries) CloseOverdueAssignments(ctx context.Context) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, closeOverdueAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignment{}
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countAssignmentsByCourse = `-- name: CountAssignmentsByCourse :one
SELECT count(*)::bigint
FROM assignments
WHERE course_id = $1
  AND lower(title) LIKE '%' || lower($2) || '%'
`

type CountAssignmentsByCourseParams struct {
	CourseID pgtype.UUID `json:"course_id"`
	Title    string      `json:"title"`
}

func (q *Queries) CountAssignmentsByCourse(ctx context.Context, arg CountAssignmentsByCourseParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignmentsByCourse, arg.CourseID, arg.Title)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countSubmissionsByAssignment = `-- name: CountSubmissionsByAssignment :one
SELECT count(*)::bigint
FROM assignment_submissions s
JOIN users u ON s.student_id = u.id
WHERE s.assignment_id = $1
  AND lower(u.full_name) LIKE '%' || lower($2) || '%'
`

type CountSubmissionsByAssignmentParams struct {
	AssignmentID pgtype.UUID `json:"assignment_id"`
	Name         string      `json:"name"`
}

func (q *Queries) CountSubmissionsByAssignment(ctx context.Context, arg CountSubmissionsByAssignmentParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubmissionsByAssignment, arg.AssignmentID, arg.Name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (course_id, title, description, due_date, status, created_by)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, course_id, title, description, due_date, status, created_at, updated_at, created_by
`

type CreateAssignmentParams struct {
	CourseID    pgtype.UUID        `json:"course_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Status      Status             `json:"status"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.CourseID,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.Status,
		arg.CreatedBy,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const createAssignmentSubmission = `-- name: CreateAssignmentSubmission :one
INSERT INTO assignment_submissions (assignment_id, student_id, submission_text, file_path, file_name)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, assignment_id, student_id, submission_text, file_path, file_name, submitted_at, grade, feedback, created_at, updated_at
`

type CreateAssignmentSubmissionParams struct {
	AssignmentID   pgtype.UUID `json:"assignment_id"`
	StudentID      pgtype.UUID `json:"student_id"`
	SubmissionText pgtype.Text `json:"submission_text"`
	FilePath       pgtype.Text `json:"file_path"`
	FileName       pgtype.Text `json:"file_name"`
}

type CreateAssignmentSubmissionRow struct {
	ID             pgtype.UUID        `json:"id"`
	AssignmentID   pgtype.UUID        `json:"assignment_id"`
	StudentID      pgtype.UUID        `json:"student_id"`
	SubmissionText pgtype.Text        `json:"submission_text"`
	FilePath       pgtype.Text        `json:"file_path"`
	FileName       pgtype.Text        `json:"file_name"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	Grade          pgtype.Int4        `json:"grade"`
	Feedback       pgtype.Text        `json:"feedback"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAssignmentSubmission(ctx context.Context, arg CreateAssignmentSubmissionParams) (CreateAssignmentSubmissionRow, error) {
	row := q.db.QueryRow(ctx, createAssignmentSubmission,
		arg.AssignmentID,
		arg.StudentID,
		arg.SubmissionText,
		arg.FilePath,
		arg.FileName,
	)
	var i CreateAssignmentSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.SubmissionText,
		&i.FilePath,
		&i.FileName,
		&i.SubmittedAt,
		&i.Grade,
		&i.Feedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :execrows
DELETE FROM assignments WHERE id = $1
`

func (q *Queries) DeleteAssignment(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAssignment, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAssignmentByCourseAndTitle = `-- name: GetAssignmentByCourseAndTitle :one
SELECT id, course_id, title, description, due_date, status, created_at, updated_at, created_by
FROM assignments
WHERE course_id = $1
  AND lower(title) = lower($2)
`

type GetAssignmentByCourseAndTitleParams struct {
	CourseID pgtype.UUID `json:"course_id"`
	Title    string      `json:"title"`
}

func (q *Queries) GetAssignmentByCourseAndTitle(ctx context.Context, arg GetAssignmentByCourseAndTitleParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentByCourseAndTitle, arg.CourseID, arg.Title)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT id, course_id, title, description, due_date, status, created_at, updated_at, created_by
FROM assignments
WHERE id = $1
`

func (q *Queries) GetAssignmentByID(ctx context.Context, id pgtype.UUID) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignmentByID, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const getSubmissionByAssignmentAndStudent = `-- name: GetSubmissionByAssignmentAndStudent :one
SELECT id, assignment_id, student_id, submission_text, file_path, file_name, submitted_at, grade, feedback, created_at, updated_at
FROM assignment_submissions
WHERE assignment_id = $1
  AND student_id = $2
`

type GetSubmissionByAssignmentAndStudentParams struct {
	AssignmentID pgtype.UUID `json:"assignment_id"`
	StudentID    pgtype.UUID `json:"student_id"`
}

type GetSubmissionByAssignmentAndStudentRow struct {
	ID             pgtype.UUID        `json:"id"`
	AssignmentID   pgtype.UUID        `json:"assignment_id"`
	StudentID      pgtype.UUID        `json:"student_id"`
	SubmissionText pgtype.Text        `json:"submission_text"`
	FilePath       pgtype.Text        `json:"file_path"`
	FileName       pgtype.Text        `json:"file_name"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	Grade          pgtype.Int4        `json:"grade"`
	Feedback       pgtype.Text        `json:"feedback"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSubmissionByAssignmentAndStudent(ctx context.Context, arg GetSubmissionByAssignmentAndStudentParams) (GetSubmissionByAssignmentAndStudentRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionByAssignmentAndStudent, arg.AssignmentID, arg.StudentID)
	var i GetSubmissionByAssignmentAndStudentRow
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.SubmissionText,
		&i.FilePath,
		&i.FileName,
		&i.SubmittedAt,
		&i.Grade,
		&i.Feedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubmissionByID = `-- name: GetSubmissionByID :one
SELECT id, assignment_id, student_id, submission_text, file_path, file_name, submitted_at, grade, feedback, created_at, updated_at
FROM assignment_submissions
WHERE id = $1
`

type GetSubmissionByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	AssignmentID   pgtype.UUID        `json:"assignment_id"`
	StudentID      pgtype.UUID        `json:"student_id"`
	SubmissionText pgtype.Text        `json:"submission_text"`
	FilePath       pgtype.Text        `json:"file_path"`
	FileName       pgtype.Text        `json:"file_name"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	Grade          pgtype.Int4        `json:"grade"`
	Feedback       pgtype.Text        `json:"feedback"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSubmissionByID(ctx context.Context, id pgtype.UUID) (GetSubmissionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSubmissionByID, id)
	var i GetSubmissionByIDRow
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.SubmissionText,
		&i.FilePath,
		&i.FileName,
		&i.SubmittedAt,
		&i.Grade,
		&i.Feedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const gradeSubmission = `-- name: GradeSubmission :one
UPDATE assignment_submissions
SET grade = $1,
    feedback = $2,
    graded_at = now(),
    updated_at = now()
WHERE id = $3
RETURNING id, assignment_id, student_id, submission_text, file_path, file_name, submitted_at, grade, feedback, created_at, updated_at
`

type GradeSubmissionParams struct {
	Grade    pgtype.Int4 `json:"grade"`
	Feedback pgtype.Text `json:"feedback"`
	ID       pgtype.UUID `json:"id"`
}

type GradeSubmissionRow struct {
	ID             pgtype.UUID        `json:"id"`
	AssignmentID   pgtype.UUID        `json:"assignment_id"`
	StudentID      pgtype.UUID        `json:"student_id"`
	SubmissionText pgtype.Text        `json:"submission_text"`
	FilePath       pgtype.Text        `json:"file_path"`
	FileName       pgtype.Text        `json:"file_name"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	Grade          pgtype.Int4        `json:"grade"`
	Feedback       pgtype.Text        `json:"feedback"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GradeSubmission(ctx context.Context, arg GradeSubmissionParams) (GradeSubmissionRow, error) {
	row := q.db.QueryRow(ctx, gradeSubmission, arg.Grade, arg.Feedback, arg.ID)
	var i GradeSubmissionRow
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.SubmissionText,
		&i.FilePath,
		&i.FileName,
		&i.SubmittedAt,
		&i.Grade,
		&i.Feedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignmentsByCourse = `-- name: ListAssignmentsByCourse :many
SELECT id, course_id, title, description, due_date, status, created_at, updated_at, created_by
FROM assignments
WHERE course_id = $1
  AND lower(title) LIKE '%' || lower($2) || '%'
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListAssignmentsByCourseParams struct {
	CourseID    pgtype.UUID `json:"course_id"`
	Title       string      `json:"title"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListAssignmentsByCourse(ctx context.Context, arg ListAssignmentsByCourseParams) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByCourse,
		arg.CourseID,
		arg.Title,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignment{}
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedAssignmentsByCourse = `-- name: ListPublishedAssignmentsByCourse :many
SELECT id, course_id, title, description, due_date, status, created_at, updated_at, created_by
FROM assignments
WHERE course_id = $1
  AND status = 'published'
ORDER BY due_date ASC
`

func (q *Queries) ListPublishedAssignmentsByCourse(ctx context.Context, courseID pgtype.UUID) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listPublishedAssignmentsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignment{}
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Description,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionsByAssignment = `-- name: ListSubmissionsByAssignment :many
SELECT s.id, s.assignment_id, s.student_id, s.submission_text, s.file_path, s.file_name, s.submitted_at, s.grade, s.feedback, s.created_at, s.updated_at,
       u.full_name AS student_name, u.email AS student_email
FROM assignment_submissions s
JOIN users u ON s.student_id = u.id
WHERE s.assignment_id = $1
  AND lower(u.full_name) LIKE '%' || lower($2) || '%'
ORDER BY s.submitted_at DESC
LIMIT $4 OFFSET $3
`

type ListSubmissionsByAssignmentParams struct {
	AssignmentID pgtype.UUID `json:"assignment_id"`
	Name         string      `json:"name"`
	OffsetCount  int32       `json:"offset_count"`
	LimitCount   int32       `json:"limit_count"`
}

type ListSubmissionsByAssignmentRow struct {
	ID             pgtype.UUID        `json:"id"`
	AssignmentID   pgtype.UUID        `json:"assignment_id"`
	StudentID      pgtype.UUID        `json:"student_id"`
	SubmissionText pgtype.Text        `json:"submission_text"`
	FilePath       pgtype.Text        `json:"file_path"`
	FileName       pgtype.Text        `json:"file_name"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	Grade          pgtype.Int4        `json:"grade"`
	Feedback       pgtype.Text        `json:"feedback"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	StudentName    string             `json:"student_name"`
	StudentEmail   string             `json:"student_email"`
}

func (q *Queries) ListSubmissionsByAssignment(ctx context.Context, arg ListSubmissionsByAssignmentParams) ([]ListSubmissionsByAssignmentRow, error) {
	rows, err := q.db.Query(ctx, listSubmissionsByAssignment,
		arg.AssignmentID,
		arg.Name,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmissionsByAssignmentRow{}
	for rows.Next() {
		var i ListSubmissionsByAssignmentRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentID,
			&i.StudentID,
			&i.SubmissionText,
			&i.FilePath,
			&i.FileName,
			&i.SubmittedAt,
			&i.Grade,
			&i.Feedback,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StudentName,
			&i.StudentEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssignment = `-- name: UpdateAssignment :one
UPDATE assignments
SET title = $1,
    description = $2,
    due_date = $3,
    status = $4,
    updated_at = now()
WHERE id = $5
RETURNING id, course_id, title, description, due_date, status, created_at, updated_at, created_by
`

type UpdateAssignmentParams struct {
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Status      Status             `json:"status"`
	ID          pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, updateAssignment,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.Status,
		arg.ID,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Description,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}
