// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: courses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCourses = `-- name: CountCourses :one
SELECT count(*)::bigint
FROM courses c
WHERE c.published = $1
  AND lower(c.title) LIKE '%' || lower($2) || '%'
`

type CountCoursesParams struct {
	Published bool   `json:"published"`
	Title     string `json:"title"`
}

func (q *Queries) CountCourses(ctx context.Context, arg CountCoursesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCourses, arg.Published, arg.Title)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countEnrolledCourses = `-- name: CountEnrolledCourses :one
SELECT count(*)::bigint
FROM courses c
JOIN enrollments e ON c.id = e.course_id
WHERE e.user_id = $1
  AND lower(c.title) LIKE '%' || lower($2) || '%'
`

type CountEnrolledCoursesParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	Title     string      `json:"title"`
}

func (q *Queries) CountEnrolledCourses(ctx context.Context, arg CountEnrolledCoursesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEnrolledCourses, arg.StudentID, arg.Title)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countEnrolledStudentsByCourse = `-- name: CountEnrolledStudentsByCourse :one
SELECT count(*)::bigint
FROM enrollments e
JOIN users u ON e.user_id = u.id
WHERE e.course_id = $1
  AND lower(u.full_name) LIKE '%' || lower($2) || '%'
`

type CountEnrolledStudentsByCourseParams struct {
	CourseID pgtype.UUID `json:"course_id"`
	Name     string      `json:"name"`
}

func (q *Queries) CountEnrolledStudentsByCourse(ctx context.Context, arg CountEnrolledStudentsByCourseParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEnrolledStudentsByCourse, arg.CourseID, arg.Name)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countInstructorCourses = `-- name: CountInstructorCourses :one
SELECT count(*)::bigint
FROM courses c
WHERE c.instructor_id = $1
  AND lower(c.title) LIKE '%' || lower($2) || '%'
`

type CountInstructorCoursesParams struct {
	InstructorID pgtype.UUID `json:"instructor_id"`
	Title        string      `json:"title"`
}

func (q *Queries) CountInstructorCourses(ctx context.Context, arg CountInstructorCoursesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInstructorCourses, arg.InstructorID, arg.Title)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (instructor_id, title, slug, description, published)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, instructor_id, title, slug, description, published, created_at, updated_at
`

type CreateCourseParams struct {
	InstructorID pgtype.UUID `json:"instructor_id"`
	Title        string      `json:"title"`
	Slug         string      `json:"slug"`
	Description  pgtype.Text `json:"description"`
	Published    bool        `json:"published"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourse,
		arg.InstructorID,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Published,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.InstructorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLesson = `-- name: CreateLesson :one
INSERT INTO lessons (course_id, title, sort_order, content)
VALUES ($1, $2, $3, $4)
RETURNING id, course_id, title, sort_order, content, created_at, updated_at
`

type CreateLessonParams struct {
	CourseID  pgtype.UUID `json:"course_id"`
	Title     string      `json:"title"`
	SortOrder int32       `json:"sort_order"`
	Content   pgtype.Text `json:"content"`
}

func (q *Queries) CreateLesson(ctx context.Context, arg CreateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, createLesson,
		arg.CourseID,
		arg.Title,
		arg.SortOrder,
		arg.Content,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.SortOrder,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCourse = `-- name: DeleteCourse :execrows
DELETE FROM courses WHERE id = $1
`

func (q *Queries) DeleteCourse(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCourse, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteEnrollment = `-- name: DeleteEnrollment :execrows
DELETE FROM enrollments
WHERE user_id = $1 AND course_id = $2
`

type DeleteEnrollmentParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	CourseID pgtype.UUID `json:"course_id"`
}

func (q *Queries) DeleteEnrollment(ctx context.Context, arg DeleteEnrollmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnrollment, arg.UserID, arg.CourseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLesson = `-- name: DeleteLesson :execrows
DELETE FROM lessons WHERE id = $1
`

func (q *Queries) DeleteLesson(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLesson, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCourseByID = `-- name: GetCourseByID :one
SELECT c.id, c.instructor_id, c.title, c.slug, c.description, c.published, c.created_at, c.updated_at,
       u.full_name AS instructor_name, u.email AS email
FROM courses c
JOIN users u ON c.instructor_id = u.id
WHERE c.id = $1
`

type GetCourseByIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	InstructorID   pgtype.UUID        `json:"instructor_id"`
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	Published      bool               `json:"published"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	InstructorName string             `json:"instructor_name"`
	Email          string             `json:"email"`
}

func (q *Queries) GetCourseByID(ctx context.Context, id pgtype.UUID) (GetCourseByIDRow, error) {
	row := q.db.QueryRow(ctx, getCourseByID, id)
	var i GetCourseByIDRow
	err := row.Scan(
		&i.ID,
		&i.InstructorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InstructorName,
		&i.Email,
	)
	return i, err
}

const getCourses = `-- name: GetCourses :many
SELECT c.id, c.instructor_id, c.title, c.slug, c.description, c.published, c.created_at, c.updated_at,
       u.full_name AS instructor_name, u.email AS email
FROM courses c
JOIN users u ON c.instructor_id = u.id
WHERE c.published = $1
  AND lower(c.title) LIKE '%' || lower($2) || '%'
ORDER BY c.created_at DESC
LIMIT $4 OFFSET $3
`

type GetCoursesParams struct {
	Published   bool   `json:"published"`
	Title       string `json:"title"`
	OffsetCount int32  `json:"offset_count"`
	LimitCount  int32  `json:"limit_count"`
}

type GetCoursesRow struct {
	ID             pgtype.UUID        `json:"id"`
	InstructorID   pgtype.UUID        `json:"instructor_id"`
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	Published      bool               `json:"published"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	InstructorName string             `json:"instructor_name"`
	Email          string             `json:"email"`
}

func (q *Queries) GetCourses(ctx context.Context, arg GetCoursesParams) ([]GetCoursesRow, error) {
	rows, err := q.db.Query(ctx, getCourses,
		arg.Published,
		arg.Title,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCoursesRow{}
	for rows.Next() {
		var i GetCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.InstructorID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstructorName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEnrolledCourses = `-- name: GetEnrolledCourses :many
SELECT c.id, c.instructor_id, c.title, c.slug, c.description, c.published, c.created_at, c.updated_at,
       u.full_name AS instructor_name, u.email AS email
FROM courses c
JOIN users u ON c.instructor_id = u.id
JOIN enrollments e ON c.id = e.course_id
WHERE e.user_id = $1
  AND lower(c.title) LIKE '%' || lower($2) || '%'
ORDER BY e.enrolled_at DESC
LIMIT $4 OFFSET $3
`

type GetEnrolledCoursesParams struct {
	StudentID   pgtype.UUID `json:"student_id"`
	Title       string      `json:"title"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type GetEnrolledCoursesRow struct {
	ID             pgtype.UUID        `json:"id"`
	InstructorID   pgtype.UUID        `json:"instructor_id"`
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	Published      bool               `json:"published"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	InstructorName string             `json:"instructor_name"`
	Email          string             `json:"email"`
}

func (q *Queries) GetEnrolledCourses(ctx context.Context, arg GetEnrolledCoursesParams) ([]GetEnrolledCoursesRow, error) {
	rows, err := q.db.Query(ctx, getEnrolledCourses,
		arg.StudentID,
		arg.Title,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnrolledCoursesRow{}
	for rows.Next() {
		var i GetEnrolledCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.InstructorID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstructorName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstructorCourses = `-- name: GetInstructorCourses :many
SELECT c.id, c.instructor_id, c.title, c.slug, c.description, c.published, c.created_at, c.updated_at,
       u.full_name AS instructor_name, u.email AS email
FROM courses c
JOIN users u ON c.instructor_id = u.id
WHERE c.instructor_id = $1
  AND lower(c.title) LIKE '%' || lower($2) || '%'
ORDER BY c.created_at DESC
LIMIT $4 OFFSET $3
`

type GetInstructorCoursesParams struct {
	InstructorID pgtype.UUID `json:"instructor_id"`
	Title        string      `json:"title"`
	OffsetCount  int32       `json:"offset_count"`
	LimitCount   int32       `json:"limit_count"`
}

type GetInstructorCoursesRow struct {
	ID             pgtype.UUID        `json:"id"`
	InstructorID   pgtype.UUID        `json:"instructor_id"`
	Title          string             `json:"title"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	Published      bool               `json:"published"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	InstructorName string             `json:"instructor_name"`
	Email          string             `json:"email"`
}

func (q *Queries) GetInstructorCourses(ctx context.Context, arg GetInstructorCoursesParams) ([]GetInstructorCoursesRow, error) {
	rows, err := q.db.Query(ctx, getInstructorCourses,
		arg.InstructorID,
		arg.Title,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInstructorCoursesRow{}
	for rows.Next() {
		var i GetInstructorCoursesRow
		if err := rows.Scan(
			&i.ID,
			&i.InstructorID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InstructorName,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonByID = `-- name: GetLessonByID :one
SELECT id, course_id, title, sort_order, content, created_at, updated_at
FROM lessons
WHERE id = $1
`

func (q *Queries) GetLessonByID(ctx context.Context, id pgtype.UUID) (Lesson, error) {
	row := q.db.QueryRow(ctx, getLessonByID, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.SortOrder,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCourseLessons = `-- name: ListCourseLessons :many
SELECT id, course_id, title, sort_order, content, created_at, updated_at
FROM lessons
WHERE course_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListCourseLessons(ctx context.Context, courseID pgtype.UUID) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listCourseLessons, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lesson{}
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.SortOrder,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrolledStudentsByCourse = `-- name: ListEnrolledStudentsByCourse :many
SELECT u.id, u.email, u.full_name, u.role, u.created_at, u.updated_at, e.enrolled_at
FROM enrollments e
JOIN users u ON e.user_id = u.id
WHERE e.course_id = $1
  AND lower(u.full_name) LIKE '%' || lower($2) || '%'
ORDER BY e.enrolled_at DESC
LIMIT $4 OFFSET $3
`

type ListEnrolledStudentsByCourseParams struct {
	CourseID    pgtype.UUID `json:"course_id"`
	Name        string      `json:"name"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

type ListEnrolledStudentsByCourseRow struct {
	ID         pgtype.UUID        `json:"id"`
	Email      string             `json:"email"`
	FullName   string             `json:"full_name"`
	Role       string             `json:"role"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	EnrolledAt pgtype.Timestamptz `json:"enrolled_at"`
}

func (q *Queries) ListEnrolledStudentsByCourse(ctx context.Context, arg ListEnrolledStudentsByCourseParams) ([]ListEnrolledStudentsByCourseRow, error) {
	rows, err := q.db.Query(ctx, listEnrolledStudentsByCourse,
		arg.CourseID,
		arg.Name,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnrolledStudentsByCourseRow{}
	for rows.Next() {
		var i ListEnrolledStudentsByCourseRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FullName,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.EnrolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstructors = `-- name: ListInstructors :many
SELECT id, email, password_hash, full_name, role, created_at, updated_at
FROM users
WHERE role = 'instructor'
ORDER BY created_at ASC
`

func (q *Queries) ListInstructors(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listInstructors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudents = `-- name: ListStudents :many
SELECT id, email, password_hash, full_name, role, created_at, updated_at
FROM users
WHERE role = 'student'
ORDER BY created_at ASC
`

func (q *Queries) ListStudents(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCourse = `-- name: UpdateCourse :one
UPDATE courses
SET title = $1,
    slug = $2,
    description = $3,
    published = $4,
    updated_at = now()
WHERE id = $5
RETURNING id, instructor_id, title, slug, description, published, created_at, updated_at
`

type UpdateCourseParams struct {
	Title       string      `json:"title"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
	Published   bool        `json:"published"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateCourse(ctx context.Context, arg UpdateCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourse,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.Published,
		arg.ID,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.InstructorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLesson = `-- name: UpdateLesson :one
UPDATE lessons
SET title = $1,
    sort_order = $2,
    content = $3,
    updated_at = now()
WHERE id = $4
RETURNING id, course_id, title, sort_order, content, created_at, updated_at
`

type UpdateLessonParams struct {
	Title     string      `json:"title"`
	SortOrder int32       `json:"sort_order"`
	Content   pgtype.Text `json:"content"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, updateLesson,
		arg.Title,
		arg.SortOrder,
		arg.Content,
		arg.ID,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.SortOrder,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
