// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnnouncement = `-- name: CreateAnnouncement :one
INSERT INTO announcements (course_id, title, content, status, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, course_id, title, content, status, created_by, created_at, updated_at
`

type CreateAnnouncementParams struct {
	CourseID  pgtype.UUID        `json:"course_id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Status    AnnouncementStatus `json:"status"`
	CreatedBy pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateAnnouncement(ctx context.Context, arg CreateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, createAnnouncement,
		arg.CourseID,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.CreatedBy,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnnouncement = `-- name: DeleteAnnouncement :execrows
DELETE FROM announcements WHERE id = $1
`

func (q *Queries) DeleteAnnouncement(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAnnouncement, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAnnouncementByID = `-- name: GetAnnouncementByID :one
SELECT id, course_id, title, content, status, created_by, created_at, updated_at
FROM announcements
WHERE id = $1
`

func (q *Queries) GetAnnouncementByID(ctx context.Context, id pgtype.UUID) (Announcement, error) {
	row := q.db.QueryRow(ctx, getAnnouncementByID, id)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCourseAnalytics = `-- name: GetCourseAnalytics :one
SELECT
    (SELECT count(*) FROM enrollments e WHERE e.course_id = $1)::bigint AS enrollments,
    (SELECT count(*) FROM assignments a WHERE a.course_id = $1)::bigint AS assignments,
    (SELECT count(*)
       FROM assignment_submissions s
       JOIN assignments a ON a.id = s.assignment_id
      WHERE a.course_id = $1)::bigint AS submissions,
    COALESCE((SELECT avg(s.grade)
       FROM assignment_submissions s
       JOIN assignments a ON a.id = s.assignment_id
      WHERE a.course_id = $1 AND s.grade IS NOT NULL), 0)::float8 AS average_grade,
    (SELECT count(*)
       FROM lessons l
      WHERE l.course_id = $1)::bigint AS lessons,
    (SELECT count(*)
       FROM lesson_progress lp
       JOIN lessons l ON l.id = lp.lesson_id
      WHERE l.course_id = $1 AND lp.completed = true)::bigint AS lesson_completions
`

type GetCourseAnalyticsRow struct {
	Enrollments       int64   `json:"enrollments"`
	Assignments       int64   `json:"assignments"`
	Submissions       int64   `json:"submissions"`
	AverageGrade      float64 `json:"average_grade"`
	Lessons           int64   `json:"lessons"`
	LessonCompletions int64   `json:"lesson_completions"`
}

func (q *Queries) GetCourseAnalytics(ctx context.Context, targetCourseID pgtype.UUID) (GetCourseAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, getCourseAnalytics, targetCourseID)
	var i GetCourseAnalyticsRow
	err := row.Scan(
		&i.Enrollments,
		&i.Assignments,
		&i.Submissions,
		&i.AverageGrade,
		&i.Lessons,
		&i.LessonCompletions,
	)
	return i, err
}

const getCourseProgress = `-- name: GetCourseProgress :one
SELECT
    count(l.id)::bigint AS total_lessons,
    count(l.id) FILTER (WHERE lp.completed = true)::bigint AS completed_lessons
FROM lessons l
LEFT JOIN lesson_progress lp
  ON lp.lesson_id = l.id AND lp.student_id = $1
WHERE l.course_id = $2
`

type GetCourseProgressParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	CourseID  pgtype.UUID `json:"course_id"`
}

type GetCourseProgressRow struct {
	TotalLessons     int64 `json:"total_lessons"`
	CompletedLessons int64 `json:"completed_lessons"`
}

func (q *Queries) GetCourseProgress(ctx context.Context, arg GetCourseProgressParams) (GetCourseProgressRow, error) {
	row := q.db.QueryRow(ctx, getCourseProgress, arg.StudentID, arg.CourseID)
	var i GetCourseProgressRow
	err := row.Scan(&i.TotalLessons, &i.CompletedLessons)
	return i, err
}

const getInstructorStats = `-- name: GetInstructorStats :one
SELECT
    (SELECT count(*) FROM courses c WHERE c.instructor_id = $1)::bigint AS courses,
    (SELECT count(*) FROM courses c WHERE c.instructor_id = $1 AND c.published = true)::bigint AS published_courses,
    (SELECT count(*)
       FROM enrollments e
       JOIN courses c ON c.id = e.course_id
      WHERE c.instructor_id = $1)::bigint AS enrollments,
    (SELECT count(DISTINCT e.user_id)
       FROM enrollments e
       JOIN courses c ON c.id = e.course_id
      WHERE c.instructor_id = $1)::bigint AS students,
    (SELECT count(*)
       FROM lessons l
       JOIN courses c ON c.id = l.course_id
      WHERE c.instructor_id = $1)::bigint AS lessons,
    (SELECT count(*)
       FROM assignments a
       JOIN courses c ON c.id = a.course_id
      WHERE c.instructor_id = $1)::bigint AS assignments,
    (SELECT count(*)
       FROM assignment_submissions s
       JOIN assignments a ON a.id = s.assignment_id
       JOIN courses c ON c.id = a.course_id
      WHERE c.instructor_id = $1)::bigint AS submissions,
    (SELECT count(*)
       FROM assignment_submissions s
       JOIN assignments a ON a.id = s.assignment_id
       JOIN courses c ON c.id = a.course_id
      WHERE c.instructor_id = $1 AND s.grade IS NULL)::bigint AS ungraded_submissions,
    (SELECT count(*)
       FROM announcements an
       JOIN courses c ON c.id = an.course_id
      WHERE c.instructor_id = $1)::bigint AS announcements
`

type GetInstructorStatsRow struct {
	Courses             int64 `json:"courses"`
	PublishedCourses    int64 `json:"published_courses"`
	Enrollments         int64 `json:"enrollments"`
	Students            int64 `json:"students"`
	Lessons             int64 `json:"lessons"`
	Assignments         int64 `json:"assignments"`
	Submissions         int64 `json:"submissions"`
	UngradedSubmissions int64 `json:"ungraded_submissions"`
	Announcements       int64 `json:"announcements"`
}

func (q *Queries) GetInstructorStats(ctx context.Context, instructorID pgtype.UUID) (GetInstructorStatsRow, error) {
	row := q.db.QueryRow(ctx, getInstructorStats, instructorID)
	var i GetInstructorStatsRow
	err := row.Scan(
		&i.Courses,
		&i.PublishedCourses,
		&i.Enrollments,
		&i.Students,
		&i.Lessons,
		&i.Assignments,
		&i.Submissions,
		&i.UngradedSubmissions,
		&i.Announcements,
	)
	return i, err
}

const getNextIncompleteLesson = `-- name: GetNextIncompleteLesson :one
SELECT l.id, l.course_id, l.title, l.sort_order, l.content, l.created_at, l.updated_at
FROM lessons l
LEFT JOIN lesson_progress lp
  ON lp.lesson_id = l.id AND lp.student_id = $1
WHERE l.course_id = $2
  AND COALESCE(lp.completed, false) = false
ORDER BY l.sort_order ASC, l.created_at ASC
LIMIT 1
`

type GetNextIncompleteLessonParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	CourseID  pgtype.UUID `json:"course_id"`
}

func (q *Queries) GetNextIncompleteLesson(ctx context.Context, arg GetNextIncompleteLessonParams) (Lesson, error) {
	row := q.db.QueryRow(ctx, getNextIncompleteLesson, arg.StudentID, arg.CourseID)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.SortOrder,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudentGradeSummary = `-- name: GetStudentGradeSummary :one
SELECT count(*)::bigint AS submitted,
       COALESCE(avg(grade), 0)::float8 AS average_grade
FROM assignment_submissions
WHERE student_id = $1
`

type GetStudentGradeSummaryRow struct {
	Submitted    int64   `json:"submitted"`
	AverageGrade float64 `json:"average_grade"`
}

func (q *Queries) GetStudentGradeSummary(ctx context.Context, studentID pgtype.UUID) (GetStudentGradeSummaryRow, error) {
	row := q.db.QueryRow(ctx, getStudentGradeSummary, studentID)
	var i GetStudentGradeSummaryRow
	err := row.Scan(&i.Submitted, &i.AverageGrade)
	return i, err
}

const getStudentStats = `-- name: GetStudentStats :one
SELECT
    (SELECT count(*) FROM enrollments e WHERE e.user_id = $1)::bigint AS enrolled_courses,
    (SELECT count(*)
       FROM lesson_progress lp
      WHERE lp.student_id = $1 AND lp.completed = true)::bigint AS completed_lessons,
    (SELECT count(*)
       FROM assignment_submissions s
      WHERE s.student_id = $1)::bigint AS submissions,
    (SELECT count(*)
       FROM assignment_submissions s
      WHERE s.student_id = $1 AND s.grade IS NOT NULL)::bigint AS graded_submissions,
    COALESCE((SELECT avg(s.grade)
       FROM assignment_submissions s
      WHERE s.student_id = $1 AND s.grade IS NOT NULL), 0)::float8 AS average_grade,
    (SELECT count(*)
       FROM assignments a
       JOIN enrollments e ON e.course_id = a.course_id AND e.user_id = $1
      WHERE a.status = 'published'
        AND NOT EXISTS (
            SELECT 1
              FROM assignment_submissions s
             WHERE s.assignment_id = a.id AND s.student_id = $1
        ))::bigint AS pending_assignments
`

type GetStudentStatsRow struct {
	EnrolledCourses    int64   `json:"enrolled_courses"`
	CompletedLessons   int64   `json:"completed_lessons"`
	Submissions        int64   `json:"submissions"`
	GradedSubmissions  int64   `json:"graded_submissions"`
	AverageGrade       float64 `json:"average_grade"`
	PendingAssignments int64   `json:"pending_assignments"`
}

func (q *Queries) GetStudentStats(ctx context.Context, studentID pgtype.UUID) (GetStudentStatsRow, error) {
	row := q.db.QueryRow(ctx, getStudentStats, studentID)
	var i GetStudentStatsRow
	err := row.Scan(
		&i.EnrolledCourses,
		&i.CompletedLessons,
		&i.Submissions,
		&i.GradedSubmissions,
		&i.AverageGrade,
		&i.PendingAssignments,
	)
	return i, err
}

const listInstructorAnnouncements = `-- name: ListInstructorAnnouncements :many
SELECT id, course_id, title, content, status, created_by, created_at, updated_at
FROM announcements
WHERE course_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInstructorAnnouncements(ctx context.Context, courseID pgtype.UUID) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listInstructorAnnouncements, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedAnnouncements = `-- name: ListPublishedAnnouncements :many
SELECT id, course_id, title, content, status, created_by, created_at, updated_at
FROM announcements
WHERE course_id = $1 AND status = 'published'
ORDER BY created_at DESC
`

func (q *Queries) ListPublishedAnnouncements(ctx context.Context, courseID pgtype.UUID) ([]Announcement, error) {
	rows, err := q.db.Query(ctx, listPublishedAnnouncements, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Announcement{}
	for rows.Next() {
		var i Announcement
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStudentGrades = `-- name: ListStudentGrades :many
SELECT s.id AS submission_id, s.assignment_id, a.title AS assignment_title,
       a.course_id, c.title AS course_title, s.grade, s.feedback, s.submitted_at,
       s.updated_at
FROM assignment_submissions s
JOIN assignments a ON a.id = s.assignment_id
JOIN courses c ON c.id = a.course_id
WHERE s.student_id = $1
ORDER BY s.updated_at DESC
`

type ListStudentGradesRow struct {
	SubmissionID    pgtype.UUID        `json:"submission_id"`
	AssignmentID    pgtype.UUID        `json:"assignment_id"`
	AssignmentTitle string             `json:"assignment_title"`
	CourseID        pgtype.UUID        `json:"course_id"`
	CourseTitle     string             `json:"course_title"`
	Grade           pgtype.Int4        `json:"grade"`
	Feedback        pgtype.Text        `json:"feedback"`
	SubmittedAt     pgtype.Timestamptz `json:"submitted_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListStudentGrades(ctx context.Context, studentID pgtype.UUID) ([]ListStudentGradesRow, error) {
	rows, err := q.db.Query(ctx, listStudentGrades, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStudentGradesRow{}
	for rows.Next() {
		var i ListStudentGradesRow
		if err := rows.Scan(
			&i.SubmissionID,
			&i.AssignmentID,
			&i.AssignmentTitle,
			&i.CourseID,
			&i.CourseTitle,
			&i.Grade,
			&i.Feedback,
			&i.SubmittedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubmissionVersions = `-- name: ListSubmissionVersions :many
SELECT id, submission_id, version, submission_text, file_path, file_name, submitted_at, created_at
FROM assignment_submission_versions
WHERE submission_id = $1
ORDER BY version DESC
`

func (q *Queries) ListSubmissionVersions(ctx context.Context, submissionID pgtype.UUID) ([]AssignmentSubmissionVersion, error) {
	rows, err := q.db.Query(ctx, listSubmissionVersions, submissionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AssignmentSubmissionVersion{}
	for rows.Next() {
		var i AssignmentSubmissionVersion
		if err := rows.Scan(
			&i.ID,
			&i.SubmissionID,
			&i.Version,
			&i.SubmissionText,
			&i.FilePath,
			&i.FileName,
			&i.SubmittedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resubmitAssignment = `-- name: ResubmitAssignment :one
WITH archived AS (
    INSERT INTO assignment_submission_versions
        (submission_id, version, submission_text, file_path, file_name, submitted_at)
    SELECT s.id,
           COALESCE((SELECT max(v.version) + 1 FROM assignment_submission_versions v WHERE v.submission_id = s.id), 1),
           s.submission_text, s.file_path, s.file_name, s.submitted_at
    FROM assignment_submissions s
    WHERE s.id = $1
),
updated AS (
    UPDATE assignment_submissions
    SET submission_text = $2,
        file_path = $3,
        file_name = $4,
        submitted_at = now(),
        grade = NULL,
        feedback = NULL,
        graded_at = NULL,
        updated_at = now()
    WHERE id = $1
    RETURNING id, assignment_id, student_id, submission_text, file_path, file_name,
              submitted_at, grade, feedback, created_at, updated_at
)
SELECT id, assignment_id, student_id, submission_text, file_path, file_name, submitted_at, grade, feedback, created_at, updated_at FROM updated
`

type ResubmitAssignmentParams struct {
	ID             pgtype.UUID `json:"id"`
	SubmissionText pgtype.Text `json:"submission_text"`
	FilePath       pgtype.Text `json:"file_path"`
	FileName       pgtype.Text `json:"file_name"`
}

type ResubmitAssignmentRow struct {
	ID             pgtype.UUID        `json:"id"`
	AssignmentID   pgtype.UUID        `json:"assignment_id"`
	StudentID      pgtype.UUID        `json:"student_id"`
	SubmissionText pgtype.Text        `json:"submission_text"`
	FilePath       pgtype.Text        `json:"file_path"`
	FileName       pgtype.Text        `json:"file_name"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	Grade          pgtype.Int4        `json:"grade"`
	Feedback       pgtype.Text        `json:"feedback"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ResubmitAssignment(ctx context.Context, arg ResubmitAssignmentParams) (ResubmitAssignmentRow, error) {
	row := q.db.QueryRow(ctx, resubmitAssignment,
		arg.ID,
		arg.SubmissionText,
		arg.FilePath,
		arg.FileName,
	)
	var i ResubmitAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.AssignmentID,
		&i.StudentID,
		&i.SubmissionText,
		&i.FilePath,
		&i.FileName,
		&i.SubmittedAt,
		&i.Grade,
		&i.Feedback,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAnnouncement = `-- name: UpdateAnnouncement :one
UPDATE announcements
SET title = $1,
    content = $2,
    status = $3,
    updated_at = now()
WHERE id = $4
RETURNING id, course_id, title, content, status, created_by, created_at, updated_at
`

type UpdateAnnouncementParams struct {
	Title   string             `json:"title"`
	Content string             `json:"content"`
	Status  AnnouncementStatus `json:"status"`
	ID      pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateAnnouncement(ctx context.Context, arg UpdateAnnouncementParams) (Announcement, error) {
	row := q.db.QueryRow(ctx, updateAnnouncement,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.ID,
	)
	var i Announcement
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertLessonProgress = `-- name: UpsertLessonProgress :one
INSERT INTO lesson_progress (student_id, lesson_id, completed, completed_at)
VALUES (
    $1,
    $2,
    $3,
    CASE WHEN $3::boolean THEN now() ELSE NULL END
)
ON CONFLICT (student_id, lesson_id) DO UPDATE
SET completed = EXCLUDED.completed,
    completed_at = CASE WHEN EXCLUDED.completed THEN now() ELSE NULL END,
    updated_at = now()
RETURNING id, student_id, lesson_id, completed, completed_at, updated_at
`

type UpsertLessonProgressParams struct {
	StudentID pgtype.UUID `json:"student_id"`
	LessonID  pgtype.UUID `json:"lesson_id"`
	Completed bool        `json:"completed"`
}

func (q *Queries) UpsertLessonProgress(ctx context.Context, arg UpsertLessonProgressParams) (LessonProgress, error) {
	row := q.db.QueryRow(ctx, upsertLessonProgress, arg.StudentID, arg.LessonID, arg.Completed)
	var i LessonProgress
	err := row.Scan(
		&i.ID,
		&i.StudentID,
		&i.LessonID,
		&i.Completed,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
