// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnnouncementStatus string

const (
	AnnouncementStatusDraft     AnnouncementStatus = "draft"
	AnnouncementStatusPublished AnnouncementStatus = "published"
)

func (e *AnnouncementStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AnnouncementStatus(s)
	case string:
		*e = AnnouncementStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AnnouncementStatus: %T", src)
	}
	return nil
}

type NullAnnouncementStatus struct {
	AnnouncementStatus AnnouncementStatus `json:"announcement_status"`
	Valid              bool               `json:"valid"` // Valid is true if AnnouncementStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAnnouncementStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AnnouncementStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AnnouncementStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAnnouncementStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AnnouncementStatus), nil
}

type Status string

const (
	StatusDraft     Status = "draft"
	StatusPublished Status = "published"
	StatusClosed    Status = "closed"
)

func (e *Status) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Status(s)
	case string:
		*e = Status(s)
	default:
		return fmt.Errorf("unsupported scan type for Status: %T", src)
	}
	return nil
}

type NullStatus struct {
	Status Status `json:"status"`
	Valid  bool   `json:"valid"` // Valid is true if Status is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatus) Scan(value interface{}) error {
	if value == nil {
		ns.Status, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Status.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Status), nil
}

type UserRole string

const (
	UserRoleStudent    UserRole = "student"
	UserRoleInstructor UserRole = "instructor"
	UserRoleAdmin      UserRole = "admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Announcement struct {
	ID        pgtype.UUID        `json:"id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	Title     string             `json:"title"`
	Content   string             `json:"content"`
	Status    AnnouncementStatus `json:"status"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Assignment struct {
	ID          pgtype.UUID        `json:"id"`
	CourseID    pgtype.UUID        `json:"course_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Status      Status             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
}

type AssignmentSubmission struct {
	ID             pgtype.UUID        `json:"id"`
	AssignmentID   pgtype.UUID        `json:"assignment_id"`
	StudentID      pgtype.UUID        `json:"student_id"`
	SubmissionText pgtype.Text        `json:"submission_text"`
	FilePath       pgtype.Text        `json:"file_path"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	Grade          pgtype.Int4        `json:"grade"`
	Feedback       pgtype.Text        `json:"feedback"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	FileName       pgtype.Text        `json:"file_name"`
	GradedAt       pgtype.Timestamptz `json:"graded_at"`
}

type AssignmentSubmissionVersion struct {
	ID             pgtype.UUID        `json:"id"`
	SubmissionID   pgtype.UUID        `json:"submission_id"`
	Version        int32              `json:"version"`
	SubmissionText pgtype.Text        `json:"submission_text"`
	FilePath       pgtype.Text        `json:"file_path"`
	FileName       pgtype.Text        `json:"file_name"`
	SubmittedAt    pgtype.Timestamptz `json:"submitted_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Course struct {
	ID           pgtype.UUID        `json:"id"`
	InstructorID pgtype.UUID        `json:"instructor_id"`
	Title        string             `json:"title"`
	Slug         string             `json:"slug"`
	Description  pgtype.Text        `json:"description"`
	Published    bool               `json:"published"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Enrollment struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	CourseID   pgtype.UUID        `json:"course_id"`
	EnrolledAt pgtype.Timestamptz `json:"enrolled_at"`
}

type Lesson struct {
	ID        pgtype.UUID        `json:"id"`
	CourseID  pgtype.UUID        `json:"course_id"`
	Title     string             `json:"title"`
	SortOrder int32              `json:"sort_order"`
	Content   pgtype.Text        `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LessonProgress struct {
	ID          pgtype.UUID        `json:"id"`
	StudentID   pgtype.UUID        `json:"student_id"`
	LessonID    pgtype.UUID        `json:"lesson_id"`
	Completed   bool               `json:"completed"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Note struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Notification struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Type      string             `json:"type"`
	Title     string             `json:"title"`
	Body      string             `json:"body"`
	Read      bool               `json:"read"`
	CourseID  pgtype.UUID        `json:"course_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PasswordResetOtp struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Email      string             `json:"email"`
	CodeHash   string             `json:"code_hash"`
	Digits     int32              `json:"digits"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	VerifiedAt pgtype.Timestamptz `json:"verified_at"`
	UsedAt     pgtype.Timestamptz `json:"used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
