// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (user_id, title, body)
VALUES ($1, $2, $3)
RETURNING id, user_id, title, body, created_at, updated_at
`

type CreateNoteParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Title  string      `json:"title"`
	Body   string      `json:"body"`
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, arg.UserID, arg.Title, arg.Body)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :execrows
DELETE FROM notes
WHERE id = $1
`

func (q *Queries) DeleteNote(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNote, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listNotes = `-- name: ListNotes :many
SELECT id, user_id, title, body, created_at, updated_at
FROM notes
WHERE ($1::uuid IS NULL OR user_id = $1)
ORDER BY created_at DESC
`

func (q *Queries) ListNotes(ctx context.Context, userID pgtype.UUID) ([]Note, error) {
	rows, err := q.db.Query(ctx, listNotes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Note{}
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET
    title = COALESCE($1, title),
    body = COALESCE($2, body),
    updated_at = now()
WHERE id = $3
RETURNING id, user_id, title, body, created_at, updated_at
`

type UpdateNoteParams struct {
	Title pgtype.Text `json:"title"`
	Body  pgtype.Text `json:"body"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote, arg.Title, arg.Body, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
