// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countNotificationsByUser = `-- name: CountNotificationsByUser :one
SELECT count(*)::bigint
FROM notifications
WHERE user_id = $1
  AND ($2::boolean = false OR read = false)
`

type CountNotificationsByUserParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	UnreadOnly bool        `json:"unread_only"`
}

func (q *Queries) CountNotificationsByUser(ctx context.Context, arg CountNotificationsByUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, countNotificationsByUser, arg.UserID, arg.UnreadOnly)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countUnreadNotificationsByUser = `-- name: CountUnreadNotificationsByUser :one
SELECT count(*)::bigint
FROM notifications
WHERE user_id = $1
  AND read = false
`

func (q *Queries) CountUnreadNotificationsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotificationsByUser, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, title, body, course_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, user_id, type, title, body, read, course_id, created_at
`

type CreateNotificationParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Type     string      `json:"type"`
	Title    string      `json:"title"`
	Body     string      `json:"body"`
	CourseID pgtype.UUID `json:"course_id"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.CourseID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Read,
		&i.CourseID,
		&i.CreatedAt,
	)
	return i, err
}

const createNotifications = `-- name: CreateNotifications :many
INSERT INTO notifications (user_id, type, title, body, course_id)
SELECT
    u.user_id,
    $1,
    $2,
    $3,
    $4
FROM unnest($5::uuid[]) AS u(user_id)
RETURNING id, user_id, type, title, body, read, course_id, created_at
`

type CreateNotificationsParams struct {
	Type     string        `json:"type"`
	Title    string        `json:"title"`
	Body     string        `json:"body"`
	CourseID pgtype.UUID   `json:"course_id"`
	UserIds  []pgtype.UUID `json:"user_ids"`
}

func (q *Queries) CreateNotifications(ctx context.Context, arg CreateNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, createNotifications,
		arg.Type,
		arg.Title,
		arg.Body,
		arg.CourseID,
		arg.UserIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Read,
			&i.CourseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteNotification = `-- name: DeleteNotification :execrows
DELETE FROM notifications
WHERE id = $1
`

func (q *Queries) DeleteNotification(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteNotification, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT id, user_id, type, title, body, read, course_id, created_at
FROM notifications
WHERE id = $1
`

func (q *Queries) GetNotificationByID(ctx context.Context, id pgtype.UUID) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotificationByID, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Read,
		&i.CourseID,
		&i.CreatedAt,
	)
	return i, err
}

const listNotificationsByUser = `-- name: ListNotificationsByUser :many
SELECT id, user_id, type, title, body, read, course_id, created_at
FROM notifications
WHERE user_id = $1
  AND ($2::boolean = false OR read = false)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListNotificationsByUserParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	UnreadOnly  bool        `json:"unread_only"`
	OffsetCount int32       `json:"offset_count"`
	LimitCount  int32       `json:"limit_count"`
}

func (q *Queries) ListNotificationsByUser(ctx context.Context, arg ListNotificationsByUserParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsByUser,
		arg.UserID,
		arg.UnreadOnly,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Notification{}
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Title,
			&i.Body,
			&i.Read,
			&i.CourseID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :execrows
UPDATE notifications
SET read = true
WHERE user_id = $1
  AND read = false
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET read = true
WHERE id = $1
  AND user_id = $2
RETURNING id, user_id, type, title, body, read, course_id, created_at
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, arg.ID, arg.UserID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Title,
		&i.Body,
		&i.Read,
		&i.CourseID,
		&i.CreatedAt,
	)
	return i, err
}
