// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordResetOTP = `-- name: CreatePasswordResetOTP :one
INSERT INTO password_reset_otps (user_id, email, code_hash, digits, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, email, code_hash, digits, expires_at, verified_at, used_at, created_at
`

type CreatePasswordResetOTPParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Email     string             `json:"email"`
	CodeHash  string             `json:"code_hash"`
	Digits    int32              `json:"digits"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetOTP(ctx context.Context, arg CreatePasswordResetOTPParams) (PasswordResetOtp, error) {
	row := q.db.QueryRow(ctx, createPasswordResetOTP,
		arg.UserID,
		arg.Email,
		arg.CodeHash,
		arg.Digits,
		arg.ExpiresAt,
	)
	var i PasswordResetOtp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.CodeHash,
		&i.Digits,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestActiveOTPByEmail = `-- name: GetLatestActiveOTPByEmail :one
SELECT id, user_id, email, code_hash, digits, expires_at, verified_at, used_at, created_at
FROM password_reset_otps
WHERE email = $1
  AND used_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestActiveOTPByEmail(ctx context.Context, email string) (PasswordResetOtp, error) {
	row := q.db.QueryRow(ctx, getLatestActiveOTPByEmail, email)
	var i PasswordResetOtp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.CodeHash,
		&i.Digits,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestVerifiedOTPByEmail = `-- name: GetLatestVerifiedOTPByEmail :one
SELECT id, user_id, email, code_hash, digits, expires_at, verified_at, used_at, created_at
FROM password_reset_otps
WHERE email = $1
  AND verified_at IS NOT NULL
  AND used_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestVerifiedOTPByEmail(ctx context.Context, email string) (PasswordResetOtp, error) {
	row := q.db.QueryRow(ctx, getLatestVerifiedOTPByEmail, email)
	var i PasswordResetOtp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.CodeHash,
		&i.Digits,
		&i.ExpiresAt,
		&i.VerifiedAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateOTPsByEmail = `-- name: InvalidateOTPsByEmail :exec
UPDATE password_reset_otps
SET used_at = now()
WHERE email = $1
  AND used_at IS NULL
`

func (q *Queries) InvalidateOTPsByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, invalidateOTPsByEmail, email)
	return err
}

const markOTPUsed = `-- name: MarkOTPUsed :exec
UPDATE password_reset_otps
SET used_at = now()
WHERE id = $1
`

func (q *Queries) MarkOTPUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOTPUsed, id)
	return err
}

const markOTPVerified = `-- name: MarkOTPVerified :exec
UPDATE password_reset_otps
SET verified_at = now()
WHERE id = $1
  AND used_at IS NULL
  AND verified_at IS NULL
`

func (q *Queries) MarkOTPVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markOTPVerified, id)
	return err
}

const purgeUsedOTPs = `-- name: PurgeUsedOTPs :execrows
DELETE FROM password_reset_otps WHERE used_at IS NOT NULL OR expires_at <= now()
`

func (q *Queries) PurgeUsedOTPs(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeUsedOTPs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
