// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*)::bigint
FROM users
WHERE ($1::text = ''
       OR lower(email) LIKE '%' || lower($1) || '%'
       OR lower(full_name) LIKE '%' || lower($1) || '%')
  AND ($2::text = '' OR role::text = $2)
`

type CountUsersParams struct {
	Search string `json:"search"`
	Role   string `json:"role"`
}

func (q *Queries) CountUsers(ctx context.Context, arg CountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, arg.Search, arg.Role)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createEnrollment = `-- name: CreateEnrollment :one
INSERT INTO enrollments (user_id, course_id)
VALUES ($1, $2)
RETURNING id, user_id, course_id, enrolled_at
`

type CreateEnrollmentParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	CourseID pgtype.UUID `json:"course_id"`
}

func (q *Queries) CreateEnrollment(ctx context.Context, arg CreateEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollment, arg.UserID, arg.CourseID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.EnrolledAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, full_name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, full_name, role, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	FullName     string `json:"full_name"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdminStats = `-- name: GetAdminStats :one
SELECT
    (SELECT count(*) FROM users)::bigint AS users,
    (SELECT count(*) FROM users WHERE role = 'student')::bigint AS students,
    (SELECT count(*) FROM users WHERE role = 'instructor')::bigint AS instructors,
    (SELECT count(*) FROM courses)::bigint AS courses,
    (SELECT count(*) FROM enrollments)::bigint AS enrollments,
    (SELECT count(*) FROM assignments)::bigint AS assignments,
    (SELECT count(*) FROM assignment_submissions)::bigint AS submissions
`

type GetAdminStatsRow struct {
	Users       int64 `json:"users"`
	Students    int64 `json:"students"`
	Instructors int64 `json:"instructors"`
	Courses     int64 `json:"courses"`
	Enrollments int64 `json:"enrollments"`
	Assignments int64 `json:"assignments"`
	Submissions int64 `json:"submissions"`
}

func (q *Queries) GetAdminStats(ctx context.Context) (GetAdminStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminStats)
	var i GetAdminStatsRow
	err := row.Scan(
		&i.Users,
		&i.Students,
		&i.Instructors,
		&i.Courses,
		&i.Enrollments,
		&i.Assignments,
		&i.Submissions,
	)
	return i, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, instructor_id, title, slug, description, published, created_at, updated_at
FROM courses
WHERE slug = $1
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.InstructorID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnrollment = `-- name: GetEnrollment :one
SELECT id, user_id, course_id, enrolled_at
FROM enrollments
WHERE user_id = $1 AND course_id = $2
`

type GetEnrollmentParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	CourseID pgtype.UUID `json:"course_id"`
}

func (q *Queries) GetEnrollment(ctx context.Context, arg GetEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollment, arg.UserID, arg.CourseID)
	var i Enrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CourseID,
		&i.EnrolledAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, role, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, full_name, role, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLessonsByCourse = `-- name: ListLessonsByCourse :many
SELECT id, course_id, title, sort_order, content, created_at, updated_at
FROM lessons
WHERE course_id = $1
ORDER BY sort_order ASC
`

func (q *Queries) ListLessonsByCourse(ctx context.Context, courseID pgtype.UUID) ([]Lesson, error) {
	rows, err := q.db.Query(ctx, listLessonsByCourse, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lesson{}
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Title,
			&i.SortOrder,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedCourses = `-- name: ListPublishedCourses :many
SELECT id, instructor_id, title, slug, description, published, created_at, updated_at
FROM courses
WHERE published = true
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPublishedCoursesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPublishedCourses(ctx context.Context, arg ListPublishedCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listPublishedCourses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.InstructorID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, full_name, role, created_at, updated_at
FROM users
WHERE ($1::text = ''
       OR lower(email) LIKE '%' || lower($1) || '%'
       OR lower(full_name) LIKE '%' || lower($1) || '%')
  AND ($2::text = '' OR role::text = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListUsersParams struct {
	Search      string `json:"search"`
	Role        string `json:"role"`
	OffsetCount int32  `json:"offset_count"`
	LimitCount  int32  `json:"limit_count"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.Role,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email = $1,
    full_name = $2,
    role = $3,
    updated_at = now()
WHERE id = $4
RETURNING id, email, password_hash, full_name, role, created_at, updated_at
`

type UpdateUserParams struct {
	Email    string      `json:"email"`
	FullName string      `json:"full_name"`
	Role     string      `json:"role"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Email,
		arg.FullName,
		arg.Role,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2,
    updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
